In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv(r"C:\Users\Saranya Jenita\Downloads\Dataset .csv")
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [3]:
df = df[['Restaurant Name',
         'Price range',
         'Aggregate rating',
         'Cuisines']]

df.head()

,Restaurant Name,Price range,Aggregate rating,Cuisines
0,Le Petit Souffle,3,4.8,"French, Japanese, Desserts"
1,Izakaya Kikufuji,3,4.5,Japanese
2,Heat - Edsa Shangri-La,4,4.4,"Seafood, Asian, Filipino, Indian"
3,Ooma,4,4.9,"Japanese, Sushi"
4,Sambo Kojin,4,4.8,"Japanese, Korean"

In [4]:
df = df.dropna()

In [5]:
df['Cuisines'] = df['Cuisines'].apply(lambda x: x.split(',')[0].strip())

In [6]:
encoder = LabelEncoder()

df['Cuisine_Label'] = encoder.fit_transform(df['Cuisines'])

In [7]:
X = df[['Price range','Aggregate rating']]
y = df['Cuisine_Label']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
model = RandomForestClassifier(random_state=42)

model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [10]:
y_pred = model.predict(X_test)

In [11]:
accuracy = accuracy_score(y_test,y_pred)

print("Accuracy:",accuracy)

Accuracy: 0.31953902566788894

In [16]:
print(classification_report(y_test, y_pred, zero_division=0))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.00      0.00      0.00        55
           3       0.00      0.00      0.00         1
           6       0.00      0.00      0.00        17
           7       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         5
          12       0.15      0.10      0.12       109
          13       0.00      0.00      0.00         6
          14       0.00      0.00      0.00         4
          15       0.00      0.00      0.00        13
          17       0.00      0.00      0.00        22
          18       0.00      0.00      0.00         4
          19       0.00      0.00      0.00         3
          20       0.00      0.00      0.00         4
          21       0.00      0.00      0.00        31
          22       0.00      0.00      0.00         1
          23       0.13      0.14      0.13       118
          25       0.00      0.00      0.00         1
          27       0.00      0.00      0.00       172
          28       0.00      0.00      0.00         1
          30       0.05      0.02      0.03        43
          33       0.07      0.08      0.08        26
          35       0.12      0.10      0.11        10
          36       0.15      0.04      0.06       140
          37       0.00      0.00      0.00         3
          38       1.00      0.11      0.19        19
          39       0.00      0.00      0.00         3
          40       0.00      0.00      0.00         1
          41       0.00      0.00      0.00         4
          43       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         3
          47       0.00      0.00      0.00        10
          49       0.50      0.03      0.06        33
          50       0.00      0.00      0.00        10
          51       0.00      0.00      0.00         1
          52       0.00      0.00      0.00         2
          54       0.14      0.02      0.04        44
          55       0.00      0.00      0.00        12
          56       0.00      0.00      0.00         2
          57       0.00      0.00      0.00         2
          58       0.00      0.00      0.00         1
          59       0.00      0.00      0.00         1
          61       0.00      0.00      0.00         2
          62       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         5
          64       0.00      0.00      0.00         1
          65       0.00      0.00      0.00         1
          66       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         8
          69       0.00      0.00      0.00        10
          71       0.00      0.00      0.00        45
          73       0.00      0.00      0.00         3
          74       0.00      0.00      0.00        44
          75       0.00      0.00      0.00         2
          76       0.00      0.00      0.00         1
          79       0.36      0.91      0.52       623
          81       0.00      0.00      0.00         3
          84       0.00      0.00      0.00         1
          86       0.00      0.00      0.00         1
          87       0.00      0.00      0.00        51
          88       0.00      0.00      0.00         2
          90       0.00      0.00      0.00         3
          92       0.00      0.00      0.00        23
          93       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         2
          97       0.00      0.00      0.00        13
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         1
         100       0.00      0.00      0.00        45
         101       0.00      0.00      0.00         2
         104       0.00      0.00      0.00         2
         105       0.00      0.00      0.00        52
         106       0.00      0.00      0.00         1
         107       0.00      0.00      0.00         2
         108       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         4
         112       0.00      0.00      0.00         4
         113       0.00      0.00      0.00         4
         114       0.00      0.00      0.00         1
         117       0.00      0.00      0.00         1
         118       0.00      0.00      0.00         1

    accuracy                           0.32      1909
   macro avg       0.03      0.02      0.02      1909
weighted avg       0.17      0.32      0.19      1909

In [13]:
sample = pd.DataFrame({
    'Price range':[3],
    'Aggregate rating':[4.5]
})

prediction = model.predict(sample)

print("Predicted Cuisine:",
      encoder.inverse_transform(prediction))

Predicted Cuisine: ['North Indian']

In [14]:
print("Cuisine Classification Model completed successfully.")

Cuisine Classification Model completed successfully.